/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Futsalarena;

/**
 *
 * @author Naufal
 */
import database.koneksidatabase;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Vinyl extends javax.swing.JFrame {

    /**
     * Creates new form JadwalFrame
     */
    public Statement st;
    public ResultSet rs;
    Connection cn = database.koneksidatabase.BukaKoneksi();
    public Vinyl() {
        initComponents();
       nampilindata();
    }
    
    private void hilangkan(){
        fieldnama.setText("");
        fieldwaktu.setText("");
        fieldpayment.setText("");
        fieldstatus.setText("");
        
        btnbooking.setText("Booking");
        
    }
    
    //Untuk menampilkan data di 
    
    private void nampilindata (){
        try {
            cn = koneksidatabase.BukaKoneksi();
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM vinyl");
            
            DefaultTableModel model = new DefaultTableModel ();
            model.addColumn("No.");
            model.addColumn("Tanggal Pemesanan");
            model.addColumn("Nama Team");
            model.addColumn("Waktu Booking");
            model.addColumn("Pembayaran");
            
            int no = 1;
            model.getDataVector ().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("tanggal_pemesanan"),
                    rs.getString("nama_team"),
                    rs.getString("waktu_booking"),
                    rs.getString("pembayaran")
            };
            model.addRow(data);
            tblData.setModel (model);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di tampilkan","Error", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbooking = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldnama = new javax.swing.JTextField();
        fieldwaktu = new javax.swing.JTextField();
        fieldpayment = new javax.swing.JTextField();
        fieldstatus = new javax.swing.JTextField();
        btnbatal = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        btnkembalikeawal = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnbooking.setText("Booking");
        btnbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnbooking);
        btnbooking.setBounds(50, 270, 410, 40);

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus);
        btnhapus.setBounds(130, 320, 67, 25);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal Pemesanan", "Nama Team", "Waktu Booking", "Pembayaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 160, 411, 107);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal Pemesanan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 130, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Team");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 70, 90, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Waktu Booking");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 100, 110, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pembayaran");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 130, 120, 16);
        getContentPane().add(fieldnama);
        fieldnama.setBounds(270, 30, 140, 30);
        getContentPane().add(fieldwaktu);
        fieldwaktu.setBounds(270, 60, 140, 30);
        getContentPane().add(fieldpayment);
        fieldpayment.setBounds(270, 90, 140, 30);
        getContentPane().add(fieldstatus);
        fieldstatus.setBounds(270, 120, 140, 30);

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnbatal);
        btnbatal.setBounds(200, 320, 61, 25);

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali);
        btnkembali.setBounds(270, 320, 77, 25);

        btnkembalikeawal.setText("Kembali ke awal");
        btnkembalikeawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalikeawalActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembalikeawal);
        btnkembalikeawal.setBounds(350, 320, 125, 25);

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn);
        updatebtn.setBounds(50, 320, 73, 25);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VINYL");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(0, java.awt.Color.white, java.awt.Color.white, null, null));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 10, 40, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 380);

        setSize(new java.awt.Dimension(521, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookingActionPerformed
        // TODO add your handling code here:
        try {
            st = cn.createStatement();
            if (fieldnama.getText().equals("") || 
                    fieldwaktu.getText().equals("") ||
                    fieldpayment.getText().equals("") ||
                    fieldstatus.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Anda belum mengisi semua form","Error", JOptionPane.HEIGHT);
            return;
            }
            
            //cek nama team sudah ada atau belom
            
            if(btnbooking.getText()== "Nama_Team"){
                String cekdata = "SELECT * FROM vinyl WHERE Nama_Team = '" + fieldwaktu.getText() + "'";
                rs = st.executeQuery(cekdata);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ups... nama team sudah ada");
                    hilangkan ();
                   
                }
            }else{
                    String masuksql = "INSERT INTO vinyl VALUES ('" + fieldnama.getText() +
                            "','" + fieldwaktu.getText() +
                            "','" + fieldpayment.getText() +
                            "','" + fieldstatus.getText() + "')";
                    
                    st.executeUpdate(masuksql);
                    JOptionPane.showMessageDialog(null, "Berhasil di booking");
                    nampilindata();
                    hilangkan();
                   
                    
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbookingActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        fieldnama.setText(tblData.getValueAt(tblData.getSelectedRow(), 1).toString() );
        fieldwaktu.setText(tblData.getValueAt(tblData.getSelectedRow(), 2).toString() );
        fieldpayment.setText(tblData.getValueAt(tblData.getSelectedRow(), 3).toString() );
        fieldstatus.setText(tblData.getValueAt(tblData.getSelectedRow(), 4).toString() );
        
        fieldnama.setEditable(false);
     
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        if (fieldnama.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih data yang ingin anda hapus");
        }else {
            int jawab = JOptionPane.showConfirmDialog(null,"Data ini akan dihapus, Lanjutkan?", "konfirmasi", JOptionPane.OK_CANCEL_OPTION);
            if (jawab == 0){
                try {
                    st = cn.createStatement();
                    String sql = "DELETE FROM vinyl WHERE tanggal_pemesanan = '" + fieldnama.getText() + "'";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                    nampilindata();
                    hilangkan();
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
                
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        hilangkan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        new Tipelapangan().setVisible(true);
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnkembalikeawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalikeawalActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
    }//GEN-LAST:event_btnkembalikeawalActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
      int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
         try
            {
                String sql="UPDATE  vinyl set tanggal_pemesanan=?,nama_team=?,waktu_booking=?,pembayaran=? WHERE tanggal_pemesanan='"+fieldnama.getText()+"'";
                
                PreparedStatement st = cn.prepareStatement(sql);
                if(ok==0)
                {
                try
                    {
                        st.setString(1,fieldnama.getText());
                        st.setString(2,fieldwaktu.getText());
                        st.setString(3,fieldpayment.getText());
                        st.setString(4,fieldstatus.getText());
                        st.executeUpdate();
                        nampilindata();

                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                        
                        
                    }catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                }
           }catch (Exception e){}
    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vinyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vinyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vinyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vinyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vinyl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnbooking;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnkembalikeawal;
    private javax.swing.JTextField fieldnama;
    private javax.swing.JTextField fieldpayment;
    private javax.swing.JTextField fieldstatus;
    private javax.swing.JTextField fieldwaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblData;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
